import { getData } from "./index.js";
/*take articles from API */
export const takeData = async function () {
  try {
    const res = await fetch(
      "http://api.exchangeratesapi.io/v1/latest?access_key=5eb804baea9b0a67b64ec3ea5f4461fb"
    );
    const data = await res.json();

    getData(data);
  } catch (err) {
    console.log(err);
  }
};
export const boxDetails = [
  {
    flag: "aed.png",
    symbol: "&#1583;.&#1573;",
    code: "AED",
    name: "United Arab Emirates dirham",
    country: "United Arab Emirates",
  },
  {
    flag: "afn.png",
    symbol: "&#1547;",
    code: "AFN",
    name: "Afghan afghani",
    country: "Afghanistan",
  },
  {
    flag: "all.png",
    symbol: "L",
    code: "ALL",
    name: "Albanian lek",
    country: "Albania",
  },
  {
    flag: "amd.png",
    symbol: "&#1423; ",
    code: "AMD",
    name: "Armenian dram",
    country: "Armenia",
  },
  {
    flag: "ang.png",
    symbol: "ƒ",
    code: "ANG",
    name: "Netherlands Antillean guilder",
    country: "Curaçao",
  },
  {
    flag: "aoa.png",
    symbol: "Kz",
    code: "AOA",
    name: "Angolan kwanza",
    country: " Angola",
  },
  {
    flag: "ars.png",
    symbol: "$",
    code: "ARS",
    name: "Argentine peso",
    country: "Argentina",
  },
  {
    flag: "aud.png",
    symbol: "$",
    code: "AUD",
    name: "Australian dollar",
    country: "Australia",
  },
  {
    flag: "awg.png",
    symbol: "ƒ",
    code: "AWG",
    name: "Aruban florin",
    country: "Aruba",
  },
  {
    flag: "azn.png",
    symbol: "&#8380;",
    code: "AZN",
    name: "	Azerbaijani manat",
    country: "Azerbaijan",
  },
  {
    flag: "bam.png",
    symbol: "KM",
    code: "BAM",
    name: "	Bosnia and Herzegovina convertible mark",
    country: " Bosnia and Herzegovina",
  },
  {
    flag: "bbd.png",
    symbol: "$",
    code: "BBD",
    name: "Barbadian dollar",
    country: " Barbados",
  },
  {
    flag: "bdt.png",
    symbol: "৳",
    code: "BDT",
    name: "Bangladeshi taka",
    country: "Bangladesh",
  },
  {
    flag: "bgn.png",
    symbol: "лв.",
    code: "BGN",
    name: "Bulgarian lev",
    country: "Bulgaria",
  },
  {
    flag: "bhd.png",
    symbol: "&#36;",
    code: "BHD",
    name: "Bahraini dinar",
    country: "Bahrain",
  },
  {
    flag: "bif.png",
    symbol: "Fr",
    code: "BIF",
    name: "Burundian franc",
    country: "Burundi",
  },
  {
    flag: "bmd.png",
    symbol: "$",
    code: "BMD",
    name: "Bermudian dollar",
    country: "Bermuda",
  },
  {
    flag: "bnd.png",
    symbol: "$",
    code: "BND",
    name: "Brunei dollar",
    country: "Singapore",
  },
  {
    flag: "bob.png",
    symbol: "Bs.",
    code: "BOB",
    name: "Bolivian boliviano",
    country: "Bolivia",
  },
  {
    flag: "brl.png",
    symbol: "R$",
    code: "BRL",
    name: "Brazilian real",
    country: "Brazil",
  },
  {
    flag: "bsd.png",
    symbol: "$",
    code: "BSD",
    name: "Bahamian dollar",
    country: "Bahamas, The",
  },
  {
    flag: "btc.png",
    symbol: "₿",
    code: "BTC",
    name: "Bitcoin",
    country: " El Salvador",
  },
  {
    flag: "btn.png",
    symbol: "Nu.",
    code: "BTN",
    name: "Bhutanese ngultrum",
    country: "Bhutan",
  },
  {
    flag: "bwp.png",
    symbol: "P",
    code: "BWP",
    name: "Botswana pula",
    country: "Botswana",
  },
  {
    flag: "byn.png",
    symbol: "Br",
    code: "BYN",
    name: "Belarusian ruble",
    country: "Belarus",
  },
  {
    flag: "byn.png",
    symbol: "Br",
    code: "BYR",
    name: "Belarusian ruble",
    country: "Belarus",
  },
  {
    flag: "bzd.png",
    symbol: "$",
    code: "BZD",
    name: "Belize dollar",
    country: "Belize",
  },
  {
    flag: "cad.png",
    symbol: "$",
    code: "CAD",
    name: "Canadian dollar",
    country: "Canada",
  },
  {
    flag: "cdf.png",
    symbol: "Fr",
    code: "CDF",
    name: "Congolese franc",
    country: "Democratic Republic of the Congo",
  },
  {
    flag: "chf.png",
    symbol: "Fr.",
    code: "CHF",
    name: "Swiss franc",
    country: "Liechtenstein",
  },
  {
    flag: "clf.png",
    symbol: "UF",
    code: "CLF",
    name: "Unidad de Fomento",
    country: "Chile",
  },
  {
    flag: "clp.png",
    symbol: "$",
    code: "CLP",
    name: "Chilean pesoUnidad de Fomento",
    country: "Chile",
  },
  {
    flag: "cny.png",
    symbol: "&yen;",
    code: "CNY",
    name: "Chinese yuan",
    country: "China",
  },
  {
    flag: "cop.png",
    symbol: "$",
    code: "COP",
    name: "Colombian peso",
    country: "Colombia",
  },
  {
    flag: "crc.png",
    symbol: "₡",
    code: "CRC",
    name: "Costa Rican colón",
    country: "Costa Rica",
  },
  {
    flag: "cuc.png",
    symbol: "$",
    code: "CUC",
    name: "Cuban peso",
    country: "Cuba",
  },
  {
    flag: "cup.png",
    symbol: "$",
    code: "CUP",
    name: "Cuban peso",
    country: "Cuba",
  },
  {
    flag: "cve.png",
    symbol: "$",
    code: "CVE",
    name: "Cape Verdean escudo",
    country: "Cape Verde",
  },
  {
    flag: "czk.png",
    symbol: "Kč",
    code: "CZK",
    name: "Czech koruna",
    country: "Czech Republic",
  },
  {
    flag: "djf.png",
    symbol: "Fr",
    code: "DJF",
    name: "Djiboutian franc",
    country: "Djibouti",
  },
  {
    flag: "dkk.png",
    symbol: "Kr",
    code: "DKK",
    name: "	Danish krone",
    country: "Faroe Islands",
  },
  {
    flag: "dop.png",
    symbol: "RD$",
    code: "DOP",
    name: "	Dominican peso",
    country: "Dominican Republic",
  },
  {
    flag: "dzd.png",
    symbol: "د.ج",
    code: "DZD",
    name: "Algerian dinar",
    country: "Algeria",
  },
  {
    flag: "egp.png",
    symbol: "£",
    code: "EGP",
    name: "Egyptian pound",
    country: "Egypt",
  },
  {
    flag: "ern.png",
    symbol: "	Nfk",
    code: "ERN",
    name: "Eritrean nakfa",
    country: "Eritrea",
  },
  {
    flag: "etb.png",
    symbol: "Br",
    code: "ETB",
    name: "Ethiopian birr",
    country: "Ethiopia",
  },
  {
    flag: "eur.png",
    symbol: "&euro;",
    code: "EUR",
    name: "Euro",
    country: "Europe Union",
  },
  {
    flag: "fjd.png",
    symbol: "$",
    code: "FJD",
    name: "Fijian dollar",
    country: "Fiji",
  },
  {
    flag: "fkp.png",
    symbol: "£",
    code: "FKP",
    name: "Falkland Islands pound",
    country: " Falkland Islands",
  },
  {
    flag: "gbp.png",
    symbol: "£",
    code: "GBP",
    name: "British pound",
    country: "United Kingdom",
  },
  {
    flag: "gel.png",
    symbol: "&#8382;",
    code: "GEL",
    name: "Georgian lari",
    country: "Georgia",
  },
  {
    flag: "ggp.png",
    symbol: "£",
    code: "GGP",
    name: "Guernsey pound",
    country: "Alderney",
  },
  {
    flag: "ghs.png",
    symbol: "₵",
    code: "GHS",
    name: "Ghanaian cedi",
    country: "Ghana",
  },
  {
    flag: "gip.png",
    symbol: "£",
    code: "GIP",
    name: "	Gibraltar pound",
    country: "Gibraltar",
  },
  {
    flag: "gmd.png",
    symbol: "D",
    code: "GMD",
    name: "	Gambian dalasi",
    country: "The Gambia",
  },
  {
    flag: "gnf.png",
    symbol: "Fr",
    code: "GNF",
    name: "Guinean franc",
    country: "Guinea",
  },
  {
    flag: "gtq.png",
    symbol: "Q",
    code: "GTQ",
    name: "Guatemalan quetzal",
    country: "Guatemala",
  },
  {
    flag: "gyd.png",
    symbol: "$",
    code: "GYD",
    name: "Guyanese dollar",
    country: "Guyana",
  },
  {
    flag: "hkd.png",
    symbol: "$",
    code: "HKD",
    name: "Hong Kong dollar",
    country: "Hong Kong",
  },
  {
    flag: "hnl.png",
    symbol: "L",
    code: "HNL",
    name: "Honduran lempira",
    country: "Honduras",
  },
  {
    flag: "hrk.png",
    symbol: "kn",
    code: "HRK",
    name: "Croatian kuna",
    country: "Croatia",
  },
  {
    flag: "htg.png",
    symbol: "G",
    code: "HTG",
    name: "Haitian gourde",
    country: "Haiti",
  },
  {
    flag: "huf.png",
    symbol: "Ft",
    code: "HUF",
    name: "Hungarian forint",
    country: "Hungary",
  },
  {
    flag: "idr.png",
    symbol: "Rp",
    code: "IDR",
    name: "Indonesian rupiah",
    country: "Indonesia",
  },
  {
    flag: "ils.png",
    symbol: "₪",
    code: "ILS",
    name: "Israeli new shekel",
    country: "Israel",
  },
  {
    flag: "imp.png",
    symbol: "£",
    code: "IMP",
    name: "Manx pound",
    country: "Isle of Man",
  },
  {
    flag: "inr.png",
    symbol: "₹",
    code: "INR",
    name: "Indian rupee",
    country: "India",
  },
  {
    flag: "iqd.png",
    symbol: "ع.د",
    code: "IQD",
    name: "	Iraqi dinar",
    country: "Iraq",
  },
  {
    flag: "irr.png",
    symbol: "&#65020;",
    code: "IRR",
    name: "Iranian rial",
    country: "Iran",
  },
  {
    flag: "isk.png",
    symbol: "kr",
    code: "ISK",
    name: "Icelandic króna",
    country: "Iceland",
  },
  {
    flag: "jep.png",
    symbol: "£",
    code: "JEP",
    name: "Jersey pound",
    country: "Jersey",
  },
  {
    flag: "jmd.png",
    symbol: "$",
    code: "JMD",
    name: "Jamaican dollar",
    country: "Jamaica",
  },
  {
    flag: "jod.png",
    symbol: "د.ا",
    code: "JOD",
    name: "	Jordanian dinar",
    country: "Jordan",
  },
  {
    flag: "jpy.png",
    symbol: "¥",
    code: "JPY",
    name: "Japanese yen",
    country: "Japan",
  },
  {
    flag: "kes.png",
    symbol: "Sh",
    code: "KES",
    name: "Kenyan shilling",
    country: "Kenya",
  },
  {
    flag: "kgs.png",
    symbol: "с",
    code: "KGS",
    name: "Kyrgyzstani som",
    country: "Kyrgyzstan",
  },
  {
    flag: "khr.png",
    symbol: "៛",
    code: "KHR",
    name: "Cambodian riel",
    country: "Cambodia",
  },
  {
    flag: "kmf.png",
    symbol: "Fr",
    code: "KMF",
    name: "Comorian franc",
    country: "Comoros",
  },
  {
    flag: "kpw.png",
    symbol: "₩",
    code: "KPW",
    name: "North Korean won",
    country: " Korea, North",
  },
  {
    flag: "krw.png",
    symbol: "₩",
    code: "KRW",
    name: "South Korean won",
    country: " Korea, South",
  },
  {
    flag: "kwd.png",
    symbol: "د.ك",
    code: "KWD",
    name: "Kuwaiti dinar",
    country: "Kuwait",
  },
  {
    flag: "kyd.png",
    symbol: "$",
    code: "KYD",
    name: "Cayman Islands dollar",
    country: "Cayman Islands",
  },
  {
    flag: "kzt.png",
    symbol: "₸",
    code: "KZT",
    name: "Kazakhstani tenge",
    country: "Kazakhstan",
  },
  {
    flag: "lak.png",
    symbol: "₭",
    code: "LAK",
    name: "Lao kip",
    country: "Laos",
  },
  {
    flag: "lbp.png",
    symbol: "ل.ل",
    code: "LBP",
    name: "	Lebanese pound",
    country: "Lebanon",
  },
  {
    flag: "lkr.png",
    symbol: "Rs",
    code: "LKR",
    name: "	Sri Lankan rupee",
    country: "Sri Lanka",
  },
  {
    flag: "lrd.png",
    symbol: "$",
    code: "LRD",
    name: "Liberian dollar",
    country: "Liberia",
  },
  {
    flag: "lsl.png",
    symbol: "L",
    code: "LSL",
    name: "Lesotho loti",
    country: "Lesotho",
  },
  {
    flag: "ltl.png",
    symbol: "LTL",
    code: "LTL",
    name: "Lithuanian litas",
    country: "Lithuania",
  },
  {
    flag: "lvl.png",
    symbol: "LVL",
    code: "LVL",
    name: "Latvian lats",
    country: "Latvia",
  },
  {
    flag: "lyd.png",
    symbol: "ل.د",
    code: "LYD",
    name: "Libyan dinar",
    country: "Libya",
  },
  {
    flag: "mad.png",
    symbol: "د.م.",
    code: "MAD",
    name: "Moroccan dirham",
    country: "Morocco",
  },
  {
    flag: "mdl.png",
    symbol: "L",
    code: "MDL",
    name: "Moldovan leu",
    country: "Moldova",
  },
  {
    flag: "mga.png",
    symbol: "Ar",
    code: "MGA",
    name: "Malagasy ariary",
    country: "Madagascar",
  },
  {
    flag: "mkd.png",
    symbol: "ден",
    code: "MKD",
    name: "Macedonian denar",
    country: "North Macedonia",
  },
  {
    flag: "mmk.png",
    symbol: "Ks",
    code: "MMK",
    name: "Burmese kyat",
    country: "Myanmar",
  },
  {
    flag: "mnt.png",
    symbol: "₮",
    code: "MNT",
    name: "Mongolian tögrög",
    country: "Mongolia",
  },
  {
    flag: "mop.png",
    symbol: "MOP$",
    code: "MOP",
    name: "Macanese pataca",
    country: "Macau",
  },
  {
    flag: "mro.png",
    symbol: "UM",
    code: "MRO",
    name: "Mauritanian ouguiya",
    country: "Mauritania",
  },
  {
    flag: "mur.png",
    symbol: "Rs",
    code: "MUR",
    name: "Mauritian rupee",
    country: "Mauritius",
  },
  {
    flag: "mvr.png",
    symbol: ".ރ",
    code: "MVR",
    name: "Maldivian rufiyaa",
    country: "Maldives",
  },
  {
    flag: "mwk.png",
    symbol: "MK",
    code: "MWK",
    name: "Malawian kwacha",
    country: "Malawi",
  },
  {
    flag: "mxn.png",
    symbol: "$",
    code: "MXN",
    name: "	Mexican peso",
    country: "Mexico",
  },
  {
    flag: "myr.png",
    symbol: "RM",
    code: "MYR",
    name: "Malaysian ringgit",
    country: "Malaysia",
  },
  {
    flag: "mzn.png",
    symbol: "MT",
    code: "MZN",
    name: "Mozambican metical",
    country: "Mozambique",
  },
  {
    flag: "nad.png",
    symbol: "$",
    code: "NAD",
    name: "Namibian dollar",
    country: "Namibia",
  },
  {
    flag: "ngn.png",
    symbol: "₦",
    code: "NGN",
    name: "Nigerian naira",
    country: "Nigeria",
  },
  {
    flag: "nio.png",
    symbol: "C$",
    code: "NIO",
    name: "Nicaraguan córdoba",
    country: "Nicaragua",
  },
  {
    flag: "nok.png",
    symbol: "kr",
    code: "NOK",
    name: "Norwegian krone",
    country: "Norway",
  },
  {
    flag: "npr.png",
    symbol: "रू",
    code: "NPR",
    name: "Nepalese rupee",
    country: "Nepal",
  },
  {
    flag: "nzd.png",
    symbol: "$",
    code: "NZD",
    name: "New Zealand dollar",
    country: " Pitcairn Islands",
  },
  {
    flag: "omr.png",
    symbol: "ر.ع.",
    code: "OMR",
    name: "Omani rial",
    country: "Oman",
  },
  {
    flag: "pab.png",
    symbol: "B/.",
    code: "PAB",
    name: "Panamanian balboa",
    country: "Panama",
  },
  {
    flag: "pen.png",
    symbol: "S/.",
    code: "PEN",
    name: "Peruvian sol",
    country: "Peru",
  },
  {
    flag: "pgk.png",
    symbol: "K",
    code: "PGK",
    name: "Papua New Guinean kina",
    country: "Papua New Guinea",
  },
  {
    flag: "php.png",
    symbol: "₱",
    code: "PHP",
    name: "Philippine peso",
    country: "Philippines",
  },
  {
    flag: "pkr.png",
    symbol: "RS",
    code: "PKR",
    name: "Pakistani rupee",
    country: "Pakistan",
  },
  {
    flag: "pln.png",
    symbol: "zł",
    code: "PLN",
    name: "Polish złoty",
    country: "Poland",
  },
  {
    flag: "pyg.png",
    symbol: "₲",
    code: "PYG",
    name: "Paraguayan guaraní",
    country: "Paraguay",
  },
  {
    flag: "qar.png",
    symbol: "ر.ق",
    code: "QAR",
    name: "Qatari riyal",
    country: "Qatar",
  },
  {
    flag: "ron.png",
    symbol: "lei",
    code: "RON",
    name: "Romanian leu",
    country: "Romania",
  },
  {
    flag: "rsd.png",
    symbol: "din.",
    code: "RSD",
    name: "Serbian dinar",
    country: "Serbia",
  },
  {
    flag: "rub.png",
    symbol: "₽",
    code: "RUB",
    name: "Russian ruble",
    country: "South Ossetia",
  },
  {
    flag: "rwf.png",
    symbol: "Fr",
    code: "RWF",
    name: "Rwandan franc",
    country: "Rwanda",
  },
  {
    flag: "sar.png",
    symbol: "﷼",
    code: "SAR",
    name: "Saudi riyal",
    country: "Saudi Arabia",
  },
  {
    flag: "sbd.png",
    symbol: "$",
    code: "SBD",
    name: "	Solomon Islands dollar",
    country: "Solomon Islands",
  },
  {
    flag: "scr.png",
    symbol: "RS",
    code: "SCR",
    name: "Seychellois rupee",
    country: "Seychelles",
  },
  {
    flag: "sdg.png",
    symbol: "ج.س.",
    code: "SDG",
    name: "Sudanese pound",
    country: "Sudan",
  },
  {
    flag: "sek.png",
    symbol: "kr",
    code: "SEK",
    name: "Swedish krona",
    country: "Sweden",
  },
  {
    flag: "sgd.png",
    symbol: "$",
    code: "SGD",
    name: "Singapore dollar",
    country: "Brunei",
  },
  {
    flag: "shp.png",
    symbol: "£",
    code: "SHP",
    name: "	Saint Helena pound",
    country: "Saint Helena",
  },
  {
    flag: "sll.png",
    symbol: "Le",
    code: "SLL",
    name: "	Sierra Leonean leone",
    country: " Sierra Leone",
  },
  {
    flag: "sos.png",
    symbol: "Sh",
    code: "SOS",
    name: "	Somali shilling",
    country: "Somalia",
  },
  {
    flag: "srd.png",
    symbol: "$",
    code: "SRD",
    name: "	Surinamese dollar",
    country: "Suriname",
  },
  {
    flag: "std.png",
    symbol: "Db",
    code: "STD",
    name: "	São Tomé and Príncipe dobra",
    country: "São Tomé and Príncipe",
  },
  {
    flag: "svc.png",
    symbol: "SVC",
    code: "SVC",
    name: "	Salvadoran colón",
    country: "El Salvador",
  },
  {
    flag: "syp.png",
    symbol: "L",
    code: "SYP",
    name: "Syrian pound",
    country: "Syria",
  },
  {
    flag: "szl.png",
    symbol: "£",
    code: "SZL",
    name: "Swazi lilangeni",
    country: "Eswatini",
  },
  {
    flag: "thb.png",
    symbol: "฿",
    code: "THB",
    name: "Thai baht",
    country: "Thailand",
  },
  {
    flag: "tjs.png",
    symbol: "с.",
    code: "TJS",
    name: "Tajikistan",
    country: "Thailand",
  },
  {
    flag: "tmt.png",
    symbol: "m.",
    code: "TMT",
    name: "Turkmenistan manat",
    country: "Turkmenistan",
  },
  {
    flag: "tnd.png",
    symbol: "د.ت",
    code: "TND",
    name: "Tunisian dinar",
    country: "Tunisia",
  },
  {
    flag: "top.png",
    symbol: "T$",
    code: "TOP",
    name: "Tongan paʻanga",
    country: "Tonga",
  },
  {
    flag: "try.png",
    symbol: "₺",
    code: "TRY",
    name: "Turkish lira",
    country: "Turkey",
  },
  {
    flag: "ttd.png",
    symbol: "$",
    code: "TTD",
    name: "Trinidad and Tobago dollar",
    country: "Trinidad and Tobago",
  },
  {
    flag: "twd.png",
    symbol: "$",
    code: "TWD",
    name: "	New Taiwan dollar",
    country: "Taiwan",
  },
  {
    flag: "tzs.png",
    symbol: "Sh",
    code: "TZS",
    name: "Tanzanian shilling",
    country: "Tanzania",
  },
  {
    flag: "uah.png",
    symbol: "₴",
    code: "UAH",
    name: "Ukrainian hryvnia",
    country: "Ukraine",
  },
  {
    flag: "ugx.png",
    symbol: "Sh",
    code: "UGX",
    name: "Ugandan shilling",
    country: "Uganda",
  },
  {
    flag: "usd.png",
    symbol: "$",
    code: "USD",
    name: "United States dollar",
    country: "United States",
  },
  {
    flag: "uyu.png",
    symbol: "$",
    code: "UYU",
    name: "Uruguayan peso",
    country: " Uruguay",
  },
  {
    flag: "uzs.png",
    symbol: "Sʻ",
    code: "UZS",
    name: "Uzbekistani soʻm",
    country: "  Uzbekistan",
  },
  {
    flag: "vef.png",
    symbol: "Bs",
    code: "VEF",
    name: "Venezuelan bolívar",
    country: "Venezuela ",
  },
  {
    flag: "vnd.png",
    symbol: "₫",
    code: "VND",
    name: "Vietnamese đồng",
    country: "Vietnam ",
  },
  {
    flag: "vuv.png",
    symbol: "Vt",
    code: "VUV",
    name: "	Vanuatu vatu",
    country: "Vanuatu ",
  },
  {
    flag: "wst.png",
    symbol: "T",
    code: "WST",
    name: "	Samoan tālā",
    country: "Samoa ",
  },
  {
    flag: "xaf.png",
    symbol: "Fr",
    code: "XAF",
    name: "Central African CFA franc",
    country: "In Central Africa ",
  },
  {
    flag: "xag.png",
    symbol: "Silver",
    code: "XAG",
    name: "Silver ",
    country: "Worldwide",
  },
  {
    flag: "xau.png",
    symbol: "Gold",
    code: "XAU",
    name: "Gold  ",
    country: "Worldwide",
  },
  {
    flag: "xcd.png",
    symbol: "$",
    code: "XCD",
    name: "Eastern Caribbean dollar  ",
    country: "Dominica",
  },
  {
    flag: "xdr.png",
    symbol: "SDR",
    code: "XDR",
    name: "Special Drawing Rights ",
    country: " IMF member countries",
  },
  {
    flag: "xof.png",
    symbol: "Fr",
    code: "XOF",
    name: "West African CFA franc ",
    country: "Benin",
  },
  {
    flag: "xpf.png",
    symbol: "₣",
    code: "XPF",
    name: "CFP franc ",
    country: "French Polynesia",
  },
  {
    flag: "yer.png",
    symbol: "﷼",
    code: "YER",
    name: "Yemeni rial",
    country: "Yemen",
  },
  {
    flag: "zar.png",
    symbol: "R",
    code: "ZAR",
    name: "South African rand",
    country: "Eswatini",
  },
  {
    flag: "zmk.png",
    symbol: "ZK",
    code: "ZMK",
    name: "Zambian kwacha",
    country: " Zambia",
  },
  {
    flag: "zmw.png",
    symbol: "ZK",
    code: "ZMW",
    name: "Zambian kwacha",
    country: "Zambia",
  },
  {
    flag: "zwl.png",
    symbol: "$",
    code: "ZWL",
    name: "Zimbabwean dollar",
    country: "Zimbabwe ",
  },
];
